# Generated by Django 3.1.3 on 2020-11-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201108_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
        migrations.AddField(
            model_name='education',
            name='Description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
