# Generated by Django 3.1.3 on 2020-11-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201108_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Description',
            new_name='description',
        ),
    ]
