# Generated by Django 3.1.3 on 2020-11-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='portfolio/images/')),
                ('projects', models.ManyToManyField(through='portfolio.Project_tool', to='portfolio.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project_tool',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='project_tool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.tool'),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(through='portfolio.Project_tool', to='portfolio.Tool'),
        ),
    ]
