# Generated by Django 3.1.3 on 2020-11-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20201123_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
