# Generated by Django 3.1.3 on 2020-11-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_tool_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cv',
        ),
    ]
